### ISSUE TITLE
Feedback from projects site

### ISSUE THREAD

**Issue by martinohanlon** [raspberrypilearning/build-a-buggy#11]
The link you sent for the parts list gave me a motor controller board that looked exactly like yours. However, after I bought it, I noticed it lacked an extra set of pins. Your picture shows 8 pins. My board has only 4 with no Ground Pin. How can I complete the project without a Ground Pin?

**Comment by MarcScott** [comment]
The link in the resource appears to show the correct board. If an incorrect board was sold, then this needs to be taken up with the supplier.
